# Минимальный набор для рабочего запроса (как в search_cian_api.py / test_fetcher MINIMAL).
# В профиль через бота подмешиваем только это — без десятков доп. фильтров, иначе API возвращает 0.
MINIMAL_CIAN_FILTER = {
    "region_id": 1,
    "min_price": 65000,
    "max_price": 75000,
    "rooms": [1, 2],
}

# Полный жёсткий набор (для ручной подстановки в БД при необходимости).
DEFAULT_CIAN_FILTER = {
    "region_id": 1,
    "min_price": 65000,
    "max_price": 75000,
    "rooms": [1, 2],
    "area_min": 35,
    "floor_pref": None,
    "foot_min": 10,
    "min_house_year": 2012,
    "repair_ids": [3],
    "renovation": None,
    # Остальные фильтры из URL (булевы 1, списки, числа)
    "bath": 1,
    "conditioner": 1,
    "currency": 2,
    "deal_type": "rent",
    "demolished_in_moscow_programm": 0,
    "dish_washer": 1,
    "engine_version": 2,
    "house_material": [1],
    "internet": 1,
    "is_by_homeowner": 1,
    "kids": 1,
    "kitchen_stove": "electric",
    "max_commission": 50,
    "mebel": 1,
    "mebel_k": 1,
    "min_balconies": 1,
    "min_ceiling_height": 2.5,
    "minfloor": 1,
    "minfloorn": 1,
    "minkarea": 10,
    "minlarea": 10,
    "minlift": 1,
    "offer_type": "flat",
    "only_flat": 1,
    "only_foot": 2,
    "parking_type": [2],
    "pets": 1,
    "phone": 1,
    "rfgr": 1,
    "room_type": 2,
    "tv": 1,
    "type": 4,
    "windows_type": 0,
    "wm": 1,
}
